[versions]
project = "2.3.21"

kotlin = "2.3.21"
dokka = "2.1.0"
buildconfig = "6.0.10"
exportPublic = "2.3.21"
reflect = "2.3.21"
vanniktech = "0.37.0"

nal-agl = "4.2.3.21"
nak-compose-code-editor = "2.3.21"
nak-kserialisation = "2.3.21"
nak-kotlinx = "2.3.21"

kotlinx-coroutines = "1.11.0"
compose = "1.11.1"
compose-material3 = "1.11.0-alpha07"
material = "1.7.3"

kotest = "6.1.11"

[libraries]
nal-agl-processor = { module = "net.akehurst.language:agl-processor", version.ref = "nal-agl" }
nal-agl-generators = { module = "net.akehurst.language:agl-generators", version.ref = "nal-agl" }
nal-kotlinx-komposite = { module = "net.akehurst.language:kotlinx-komposite", version.ref = "nal-agl" }

nak-compose-code-editor-api = { module = "net.akehurst.kotlin.compose:code-editor-api", version.ref = "nak-compose-code-editor" }
nak-compose-code-editor = {module="net.akehurst.kotlin.compose:code-editor",version.ref = "nak-compose-code-editor" }

compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }

nak-kserialisation-json = { module = "net.akehurst.kotlin.kserialisation:kserialisation-json", version.ref = "nak-kserialisation" }
nak-json = { module = "net.akehurst.kotlin.kserialisation:json", version.ref = "nak-kserialisation" }
nak-kotlinx-logging-api = { module = "net.akehurst.kotlinx:kotlinx-logging-api", version.ref = "nak-kotlinx" }
nak-kotlinx-logging-common = { module = "net.akehurst.kotlinx:kotlinx-logging-common", version.ref = "nak-kotlinx" }
nak-kotlinx-collections = { module = "net.akehurst.kotlinx:kotlinx-collections", version.ref = "nak-kotlinx" }
nak-kotlinx-reflect = { module = "net.akehurst.kotlinx:kotlinx-reflect", version.ref = "nak-kotlinx" }
#nak-html-builder = { module = "net.akehurst.kotlin.html5:html-builder", version.ref = "nak-html-builder" }
#nak-codemirror-api = { module = "net.akehurst.kotlin.editor:codemirror-api", version.ref = "nak-codemirror-api" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "material" }

[bundles]
compose = ["compose-material3", "compose-runtime", "compose-foundation", "compose-ui", "material-icons-core", "compose-resources"]


[plugins]
kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
exportPublic =  { id = "net.akehurst.kotlin.gradle.plugin.exportPublic", version.ref = "exportPublic" }
reflect =  { id = "net.akehurst.kotlinx.kotlinx-reflect-gradle-plugin", version.ref = "reflect" }
buildconfig =  { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
vanniktech-maven-publish = { id="com.vanniktech.maven.publish", version.ref="vanniktech" }

compose = { id="org.jetbrains.compose", version.ref="compose" }
kotlin-compose = { id="org.jetbrains.kotlin.plugin.compose", version.ref="kotlin" }