[versions]
project = "2.3.21-SNAPSHOT"

kotlin = "2.3.21"
dokka = "2.1.0"
buildconfig = "6.0.7"
exportPublic = "2.3.21-SNAPSHOT"
credentials = "3.0"
compose = "1.11.1"

nal-agl = "4.2.3.21-SNAPSHOT"
nal-editor = "2.3.21-SNAPSHOT"

nak-compose = "2.3.21-SNAPSHOT"
nak-codemirror-editor = "6.0.1"

nak-html-builder = "2.3.21-SNAPSHOT"

compose-material3 = "1.11.0-alpha07"
material = "1.7.3"
compose-navigation = "2.9.2"
kotlinx-coroutines = "1.11.0"

ktor = "3.5.1"
slf4j="2.0.16"

korlibs = "6.0.1"

[libraries]
nal-agl-processor = { module = "net.akehurst.language:agl-processor", version.ref = "nal-agl" }

nak-html-builder = { module = "net.akehurst.kotlin.html5:html-builder", version.ref = "nak-html-builder" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

nale-agl-editor-browser-worker = {module="net.akehurst.language.editor:agl-editor-browser-worker",version.ref = "nal-editor" }
nale-agl-language-service = {module="net.akehurst.language.editor:agl-language-service",version.ref = "nal-editor" }
nale-agl-editor-browser-agl = {module="net.akehurst.language.editor:agl-editor-browser-agl",version.ref = "nal-editor" }
nale-agl-editor-browser-ace = {module="net.akehurst.language.editor:agl-editor-browser-ace",version.ref = "nal-editor" }
nale-agl-editor-browser-monaco = {module="net.akehurst.language.editor:agl-editor-browser-monaco",version.ref = "nal-editor" }
nale-agl-editor-browser-codemirror = {module="net.akehurst.language.editor:agl-editor-browser-codemirror",version.ref = "nal-editor" }
nale-agl-editor-browser-ck = {module="net.akehurst.language.editor:agl-editor-browser-ck",version.ref = "nal-editor" }
nale-agl-editor-compose = {module="net.akehurst.language.editor:agl-editor-compose",version.ref = "nal-editor" }
nale-agl-editor-common = {module="net.akehurst.language.editor:agl-editor-common",version.ref = "nal-editor" }

nak-codemirror-api-realisation = {module="net.akehurst.kotlin:codemirror-api-realisation",version.ref = "nak-codemirror-editor" }
nak-compose-code-editor = {module="net.akehurst.kotlin.compose:code-editor",version.ref = "nak-compose" }
nak-compose-components = { module = "net.akehurst.kotlin.compose:components", version.ref = "nak-compose" }
nak-compose-layout-multipane = { module = "net.akehurst.kotlin.compose:layout-multipane", version.ref = "nak-compose" }

compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "material" }
compose-navigation = {module="org.jetbrains.androidx.navigation:navigation-compose", version.ref = "compose-navigation"}

ktor-websockets = { module="io.ktor:ktor-websockets", version.ref = "ktor" }
ktor-server = { module="io.ktor:ktor-server", version.ref = "ktor" }
ktor-server-core = { module="io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-jetty = { module="io.ktor:ktor-server-jetty", version.ref = "ktor" }

slf4j-simple = {module="org.slf4j:slf4j-simple", version.ref="slf4j"}

korlibs-io = {module="com.soywiz:korlibs-io", version.ref="korlibs"}

[bundles]
compose = ["compose-material3", "compose-runtime", "compose-foundation", "compose-ui", "material-icons-core", "compose-resources","compose-navigation"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
exportPublic =  { id = "net.akehurst.kotlin.gradle.plugin.exportPublic", version.ref = "exportPublic" }
buildconfig =  { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
credentials =  { id = "nu.studer.credentials", version.ref = "credentials" }

compose = { id="org.jetbrains.compose", version.ref="compose" }
kotlin-compose = { id="org.jetbrains.kotlin.plugin.compose", version.ref="kotlin" }
